export const UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT';
export const ADD_POST = 'ADD_POST';

export const UPDATE_NEW_MESSAGE_TEXT = 'UPDATE_NEW_MESSAGE_TEXT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
